<?php

/**
 * Theme registry — SATU sumber kebenaran untuk semua tema landing page.
 *
 * Menambah tema baru cukup satu entri di sini + komponen React di
 * resources/assets/js/templates/ + blok CSS `.theme-<key>` di landing.css.
 * Backend (validasi, UI CMS, props Inertia) membaca semuanya dari file ini.
 *
 * Struktur per entri:
 *   key  => [
 *     'name'        => string,  // label di CMS/picker
 *     'category'    => 'institutional' | 'umkm',   // pengelompokan UI
 *     'description' => string,  // deskripsi singkat di CMS
 *     'icon'        => string,  // ikon Tabler (tanpa prefix "ti ti-")
 *     'palette'     => ['primary' => ..., 'primary-dark' => ...],
 *
 *     // Preset desain — diterapkan OTOMATIS saat tema dipilih (lihat
 *     // ThemeCustomizerContext). Key sama dengan knob Theme Settings:
 *     //   font/radius/nav/card/button  => key di presets.js (FONT_OPTIONS dll.)
 *     //   dark                         => bool
 *     //   sectionVariants              => canonical section key => variant key
 *     //                                  (daftar variant: registry.js)
 *     //   sectionColors                => canonical section key => [bg, text, accent]
 *     'preset'     => [
 *         'font' => 'modern', 'radius' => 'default', 'nav' => 'glass',
 *         'card' => 'solid', 'button' => 'default', 'dark' => false,
 *         'sectionVariants' => ['hero' => 'hero_2', 'cta' => 'cta_1'],
 *         'sectionColors' => ['hero' => ['bg' => '#f8f4ec']],
 *     ],
 *   ]
 */
return [

    // ── Institusi / platform (default) ────────────────────────────────
    'modern' => [
        'name'        => 'Modern',
        'category'    => 'institutional',
        'description' => 'Visual progresif dengan pengalaman digital yang dinamis.',
        'icon'        => 'sparkles',
        'palette' => ['primary' => '#3755a9', 'primary-dark' => '#2c4487', 'accent' => '#40329a', 'background' => '#fcfcfd', 'card' => '#ffffff', 'foreground' => '#181b25', 'muted' => '#585d6a', 'border' => '#dadce2', 'tint' => '#eff1f5'],
        'preset' => [
            'designFamily' => 'studio', 'heroFill' => false, 'density' => 'standard', 'elevation' => 'soft',
            'font' => 'modern', 'radius' => 'rounded', 'nav' => 'glass',
            'card' => 'solid', 'button' => 'default', 'dark' => false,
            'sectionVariants' => [
                'pageheader' => 'pageheader_1',
                'navbar' => 'navbar_2',
                'topbar' => 'topbar_1',
                'hero' => 'hero_2',
                'product' => 'product_1',
                'statistic' => 'statistic_1',
                'feature' => 'feature_1',
                'testimonial' => 'testimonial_1',
                'client' => 'client_1',
                'faq' => 'faq_1',
                'pengumuman' => 'pengumuman_1',
                'cta' => 'cta_1',
                'price' => 'price_1',
                'footer' => 'footer_1',
            ],
            'sectionColors' => [
                'pageheader' => ['bg' => '#fcfcfd', 'text' => '#181b25', 'heading' => '#181b25', 'accent' => '#3755a9', 'pretext_color' => '#3755a9', 'text_color' => '#181b25', 'posttext_color' => '#585d6a'],
                'navbar' => ['bg' => '#fcfcfd', 'text' => '#181b25', 'heading' => '#181b25', 'accent' => '#3755a9', 'pretext_color' => '#3755a9', 'text_color' => '#181b25', 'posttext_color' => '#585d6a'],
                'topbar' => ['bg' => '#eff1f5', 'text' => '#181b25', 'heading' => '#181b25', 'accent' => '#3755a9', 'pretext_color' => '#3755a9', 'text_color' => '#181b25', 'posttext_color' => '#585d6a'],
                'hero' => ['bg' => '#eff1f5', 'text' => '#181b25', 'heading' => '#181b25', 'accent' => '#3755a9', 'pretext_color' => '#3755a9', 'text_color' => '#181b25', 'posttext_color' => '#585d6a'],
                'product' => ['bg' => '#fcfcfd', 'text' => '#181b25', 'heading' => '#181b25', 'accent' => '#3755a9', 'pretext_color' => '#3755a9', 'text_color' => '#181b25', 'posttext_color' => '#585d6a'],
                'statistic' => ['bg' => '#eff1f5', 'text' => '#181b25', 'heading' => '#181b25', 'accent' => '#3755a9', 'pretext_color' => '#3755a9', 'text_color' => '#181b25', 'posttext_color' => '#585d6a'],
                'feature' => ['bg' => '#fcfcfd', 'text' => '#181b25', 'heading' => '#181b25', 'accent' => '#3755a9', 'pretext_color' => '#3755a9', 'text_color' => '#181b25', 'posttext_color' => '#585d6a'],
                'testimonial' => ['bg' => '#fcfcfd', 'text' => '#181b25', 'heading' => '#181b25', 'accent' => '#3755a9', 'pretext_color' => '#3755a9', 'text_color' => '#181b25', 'posttext_color' => '#585d6a'],
                'client' => ['bg' => '#eff1f5', 'text' => '#181b25', 'heading' => '#181b25', 'accent' => '#3755a9', 'pretext_color' => '#3755a9', 'text_color' => '#181b25', 'posttext_color' => '#585d6a'],
                'faq' => ['bg' => '#fcfcfd', 'text' => '#181b25', 'heading' => '#181b25', 'accent' => '#3755a9', 'pretext_color' => '#3755a9', 'text_color' => '#181b25', 'posttext_color' => '#585d6a'],
                'pengumuman' => ['bg' => '#fcfcfd', 'text' => '#181b25', 'heading' => '#181b25', 'accent' => '#3755a9', 'pretext_color' => '#3755a9', 'text_color' => '#181b25', 'posttext_color' => '#585d6a'],
                'cta' => ['bg' => '#2c4487', 'text' => '#ffffff', 'heading' => '#ffffff', 'accent' => '#ffffff', 'pretext_color' => '#ffffff', 'text_color' => '#ffffff', 'posttext_color' => '#ffffff'],
                'price' => ['bg' => '#fcfcfd', 'text' => '#181b25', 'heading' => '#181b25', 'accent' => '#3755a9', 'pretext_color' => '#3755a9', 'text_color' => '#181b25', 'posttext_color' => '#585d6a'],
                'footer' => ['bg' => '#fcfcfd', 'text' => '#181b25', 'heading' => '#181b25', 'accent' => '#3755a9', 'pretext_color' => '#3755a9', 'text_color' => '#181b25', 'posttext_color' => '#585d6a'],
            ],
        ],
    ],
    'editorial' => [
        'name'        => 'Editorial',
        'category'    => 'institutional',
        'description' => 'Berorientasi konten dengan tipografi dan berita yang kuat.',
        'icon'        => 'news',
        'palette' => ['primary' => '#a65536', 'primary-dark' => '#83442a', 'accent' => '#967631', 'background' => '#fdfcfc', 'card' => '#ffffff', 'foreground' => '#251c18', 'muted' => '#6a5d58', 'border' => '#e2dcda', 'tint' => '#f5f1ef'],
        'preset' => [
            'designFamily' => 'editorial', 'heroFill' => false, 'density' => 'standard', 'elevation' => 'soft',
            'font' => 'serif', 'radius' => 'square', 'nav' => 'solid',
            'card' => 'outline', 'button' => 'default', 'dark' => false,
            'sectionVariants' => [
                'pageheader' => 'pageheader_7',
                'navbar' => 'navbar_7',
                'topbar' => 'topbar_4',
                'hero' => 'hero_6',
                'product' => 'product_8',
                'statistic' => 'statistic_8',
                'feature' => 'feature_7',
                'testimonial' => 'testimonial_8',
                'client' => 'client_8',
                'faq' => 'faq_1',
                'pengumuman' => 'pengumuman_8',
                'cta' => 'cta_7',
                'price' => 'price_6',
                'footer' => 'footer_6',
            ],
            'sectionColors' => [
                'pageheader' => ['bg' => '#fdfcfc', 'text' => '#251c18', 'heading' => '#251c18', 'accent' => '#a65536', 'pretext_color' => '#a65536', 'text_color' => '#251c18', 'posttext_color' => '#6a5d58'],
                'navbar' => ['bg' => '#fdfcfc', 'text' => '#251c18', 'heading' => '#251c18', 'accent' => '#a65536', 'pretext_color' => '#a65536', 'text_color' => '#251c18', 'posttext_color' => '#6a5d58'],
                'topbar' => ['bg' => '#f5f1ef', 'text' => '#251c18', 'heading' => '#251c18', 'accent' => '#a65536', 'pretext_color' => '#a65536', 'text_color' => '#251c18', 'posttext_color' => '#6a5d58'],
                'hero' => ['bg' => '#f5f1ef', 'text' => '#251c18', 'heading' => '#251c18', 'accent' => '#a65536', 'pretext_color' => '#a65536', 'text_color' => '#251c18', 'posttext_color' => '#6a5d58'],
                'product' => ['bg' => '#fdfcfc', 'text' => '#251c18', 'heading' => '#251c18', 'accent' => '#a65536', 'pretext_color' => '#a65536', 'text_color' => '#251c18', 'posttext_color' => '#6a5d58'],
                'statistic' => ['bg' => '#f5f1ef', 'text' => '#251c18', 'heading' => '#251c18', 'accent' => '#a65536', 'pretext_color' => '#a65536', 'text_color' => '#251c18', 'posttext_color' => '#6a5d58'],
                'feature' => ['bg' => '#fdfcfc', 'text' => '#251c18', 'heading' => '#251c18', 'accent' => '#a65536', 'pretext_color' => '#a65536', 'text_color' => '#251c18', 'posttext_color' => '#6a5d58'],
                'testimonial' => ['bg' => '#fdfcfc', 'text' => '#251c18', 'heading' => '#251c18', 'accent' => '#a65536', 'pretext_color' => '#a65536', 'text_color' => '#251c18', 'posttext_color' => '#6a5d58'],
                'client' => ['bg' => '#f5f1ef', 'text' => '#251c18', 'heading' => '#251c18', 'accent' => '#a65536', 'pretext_color' => '#a65536', 'text_color' => '#251c18', 'posttext_color' => '#6a5d58'],
                'faq' => ['bg' => '#fdfcfc', 'text' => '#251c18', 'heading' => '#251c18', 'accent' => '#a65536', 'pretext_color' => '#a65536', 'text_color' => '#251c18', 'posttext_color' => '#6a5d58'],
                'pengumuman' => ['bg' => '#fdfcfc', 'text' => '#251c18', 'heading' => '#251c18', 'accent' => '#a65536', 'pretext_color' => '#a65536', 'text_color' => '#251c18', 'posttext_color' => '#6a5d58'],
                'cta' => ['bg' => '#83442a', 'text' => '#ffffff', 'heading' => '#ffffff', 'accent' => '#ffffff', 'pretext_color' => '#ffffff', 'text_color' => '#ffffff', 'posttext_color' => '#ffffff'],
                'price' => ['bg' => '#fdfcfc', 'text' => '#251c18', 'heading' => '#251c18', 'accent' => '#a65536', 'pretext_color' => '#a65536', 'text_color' => '#251c18', 'posttext_color' => '#6a5d58'],
                'footer' => ['bg' => '#fdfcfc', 'text' => '#251c18', 'heading' => '#251c18', 'accent' => '#a65536', 'pretext_color' => '#a65536', 'text_color' => '#251c18', 'posttext_color' => '#6a5d58'],
            ],
        ],
    ],
    'corporate' => [
        'name'        => 'Corporate',
        'category'    => 'institutional',
        'description' => 'Tampilan mewah dan elegan untuk institusi serta mitra korporat.',
        'icon'        => 'building-skyscraper',
        'palette' => ['primary' => '#8b652d', 'primary-dark' => '#684c22', 'accent' => '#7b7b28', 'background' => '#fdfdfc', 'card' => '#ffffff', 'foreground' => '#252018', 'muted' => '#6a6358', 'border' => '#e2dfda', 'tint' => '#f5f3ef'],
        'preset' => [
            'designFamily' => 'atelier', 'heroFill' => false, 'density' => 'standard', 'elevation' => 'soft',
            'font' => 'serif', 'radius' => 'default', 'nav' => 'dark',
            'card' => 'elevated', 'button' => 'default', 'dark' => false,
            'sectionVariants' => [
                'pageheader' => 'pageheader_2',
                'navbar' => 'navbar_3',
                'topbar' => 'topbar_4',
                'hero' => 'hero_5',
                'product' => 'product_5',
                'statistic' => 'statistic_6',
                'feature' => 'feature_6',
                'testimonial' => 'testimonial_6',
                'client' => 'client_8',
                'faq' => 'faq_5',
                'pengumuman' => 'pengumuman_3',
                'cta' => 'cta_3',
                'price' => 'price_3',
                'footer' => 'footer_6',
            ],
            'sectionColors' => [
                'pageheader' => ['bg' => '#fdfdfc', 'text' => '#252018', 'heading' => '#252018', 'accent' => '#8b652d', 'pretext_color' => '#8b652d', 'text_color' => '#252018', 'posttext_color' => '#6a6358'],
                'navbar' => ['bg' => '#fdfdfc', 'text' => '#252018', 'heading' => '#252018', 'accent' => '#8b652d', 'pretext_color' => '#8b652d', 'text_color' => '#252018', 'posttext_color' => '#6a6358'],
                'topbar' => ['bg' => '#f5f3ef', 'text' => '#252018', 'heading' => '#252018', 'accent' => '#8b652d', 'pretext_color' => '#8b652d', 'text_color' => '#252018', 'posttext_color' => '#6a6358'],
                'hero' => ['bg' => '#f5f3ef', 'text' => '#252018', 'heading' => '#252018', 'accent' => '#8b652d', 'pretext_color' => '#8b652d', 'text_color' => '#252018', 'posttext_color' => '#6a6358'],
                'product' => ['bg' => '#fdfdfc', 'text' => '#252018', 'heading' => '#252018', 'accent' => '#8b652d', 'pretext_color' => '#8b652d', 'text_color' => '#252018', 'posttext_color' => '#6a6358'],
                'statistic' => ['bg' => '#f5f3ef', 'text' => '#252018', 'heading' => '#252018', 'accent' => '#8b652d', 'pretext_color' => '#8b652d', 'text_color' => '#252018', 'posttext_color' => '#6a6358'],
                'feature' => ['bg' => '#fdfdfc', 'text' => '#252018', 'heading' => '#252018', 'accent' => '#8b652d', 'pretext_color' => '#8b652d', 'text_color' => '#252018', 'posttext_color' => '#6a6358'],
                'testimonial' => ['bg' => '#fdfdfc', 'text' => '#252018', 'heading' => '#252018', 'accent' => '#8b652d', 'pretext_color' => '#8b652d', 'text_color' => '#252018', 'posttext_color' => '#6a6358'],
                'client' => ['bg' => '#f5f3ef', 'text' => '#252018', 'heading' => '#252018', 'accent' => '#8b652d', 'pretext_color' => '#8b652d', 'text_color' => '#252018', 'posttext_color' => '#6a6358'],
                'faq' => ['bg' => '#fdfdfc', 'text' => '#252018', 'heading' => '#252018', 'accent' => '#8b652d', 'pretext_color' => '#8b652d', 'text_color' => '#252018', 'posttext_color' => '#6a6358'],
                'pengumuman' => ['bg' => '#fdfdfc', 'text' => '#252018', 'heading' => '#252018', 'accent' => '#8b652d', 'pretext_color' => '#8b652d', 'text_color' => '#252018', 'posttext_color' => '#6a6358'],
                'cta' => ['bg' => '#684c22', 'text' => '#ffffff', 'heading' => '#ffffff', 'accent' => '#ffffff', 'pretext_color' => '#ffffff', 'text_color' => '#ffffff', 'posttext_color' => '#ffffff'],
                'price' => ['bg' => '#fdfdfc', 'text' => '#252018', 'heading' => '#252018', 'accent' => '#8b652d', 'pretext_color' => '#8b652d', 'text_color' => '#252018', 'posttext_color' => '#6a6358'],
                'footer' => ['bg' => '#fdfdfc', 'text' => '#252018', 'heading' => '#252018', 'accent' => '#8b652d', 'pretext_color' => '#8b652d', 'text_color' => '#252018', 'posttext_color' => '#6a6358'],
            ],
        ],
    ],
    'launch' => [
        'name'        => 'Launch UI',
        'category'    => 'institutional',
        'description' => 'Desain segar dengan hero, fitur, produk, statistik, dan CTA yang dapat dikelola penuh.',
        'icon'        => 'rocket',
        'palette' => ['primary' => '#3d37a9', 'primary-dark' => '#302c87', 'accent' => '#61329a', 'background' => '#fcfcfd', 'card' => '#ffffff', 'foreground' => '#191825', 'muted' => '#59586a', 'border' => '#dadae2', 'tint' => '#f0eff5'],
        'preset' => [
            'designFamily' => 'bento', 'heroFill' => false, 'density' => 'standard', 'elevation' => 'soft',
            'font' => 'sora', 'radius' => 'rounded', 'nav' => 'primary',
            'card' => 'outline', 'button' => 'pill', 'dark' => false,
            'sectionVariants' => [
                'pageheader' => 'pageheader_7',
                'navbar' => 'navbar_4',
                'topbar' => 'topbar_6',
                'hero' => 'hero_7',
                'product' => 'product_6',
                'statistic' => 'statistic_4',
                'feature' => 'feature_5',
                'testimonial' => 'testimonial_6',
                'client' => 'client_6',
                'faq' => 'faq_7',
                'pengumuman' => 'pengumuman_5',
                'cta' => 'cta_6',
                'price' => 'price_7',
                'footer' => 'footer_6',
            ],
            'sectionColors' => [
                'pageheader' => ['bg' => '#fcfcfd', 'text' => '#191825', 'heading' => '#191825', 'accent' => '#3d37a9', 'pretext_color' => '#3d37a9', 'text_color' => '#191825', 'posttext_color' => '#59586a'],
                'navbar' => ['bg' => '#fcfcfd', 'text' => '#191825', 'heading' => '#191825', 'accent' => '#3d37a9', 'pretext_color' => '#3d37a9', 'text_color' => '#191825', 'posttext_color' => '#59586a'],
                'topbar' => ['bg' => '#f0eff5', 'text' => '#191825', 'heading' => '#191825', 'accent' => '#3d37a9', 'pretext_color' => '#3d37a9', 'text_color' => '#191825', 'posttext_color' => '#59586a'],
                'hero' => ['bg' => '#f0eff5', 'text' => '#191825', 'heading' => '#191825', 'accent' => '#3d37a9', 'pretext_color' => '#3d37a9', 'text_color' => '#191825', 'posttext_color' => '#59586a'],
                'product' => ['bg' => '#fcfcfd', 'text' => '#191825', 'heading' => '#191825', 'accent' => '#3d37a9', 'pretext_color' => '#3d37a9', 'text_color' => '#191825', 'posttext_color' => '#59586a'],
                'statistic' => ['bg' => '#f0eff5', 'text' => '#191825', 'heading' => '#191825', 'accent' => '#3d37a9', 'pretext_color' => '#3d37a9', 'text_color' => '#191825', 'posttext_color' => '#59586a'],
                'feature' => ['bg' => '#fcfcfd', 'text' => '#191825', 'heading' => '#191825', 'accent' => '#3d37a9', 'pretext_color' => '#3d37a9', 'text_color' => '#191825', 'posttext_color' => '#59586a'],
                'testimonial' => ['bg' => '#fcfcfd', 'text' => '#191825', 'heading' => '#191825', 'accent' => '#3d37a9', 'pretext_color' => '#3d37a9', 'text_color' => '#191825', 'posttext_color' => '#59586a'],
                'client' => ['bg' => '#f0eff5', 'text' => '#191825', 'heading' => '#191825', 'accent' => '#3d37a9', 'pretext_color' => '#3d37a9', 'text_color' => '#191825', 'posttext_color' => '#59586a'],
                'faq' => ['bg' => '#fcfcfd', 'text' => '#191825', 'heading' => '#191825', 'accent' => '#3d37a9', 'pretext_color' => '#3d37a9', 'text_color' => '#191825', 'posttext_color' => '#59586a'],
                'pengumuman' => ['bg' => '#fcfcfd', 'text' => '#191825', 'heading' => '#191825', 'accent' => '#3d37a9', 'pretext_color' => '#3d37a9', 'text_color' => '#191825', 'posttext_color' => '#59586a'],
                'cta' => ['bg' => '#302c87', 'text' => '#ffffff', 'heading' => '#ffffff', 'accent' => '#ffffff', 'pretext_color' => '#ffffff', 'text_color' => '#ffffff', 'posttext_color' => '#ffffff'],
                'price' => ['bg' => '#fcfcfd', 'text' => '#191825', 'heading' => '#191825', 'accent' => '#3d37a9', 'pretext_color' => '#3d37a9', 'text_color' => '#191825', 'posttext_color' => '#59586a'],
                'footer' => ['bg' => '#fcfcfd', 'text' => '#191825', 'heading' => '#191825', 'accent' => '#3d37a9', 'pretext_color' => '#3d37a9', 'text_color' => '#191825', 'posttext_color' => '#59586a'],
            ],
        ],
    ],
    'aurora' => [
        'name'        => 'Aurora',
        'category'    => 'institutional',
        'description' => 'Permukaan gelap, tipografi tegas, dan aksen warna yang terarah.',
        'icon'        => 'brand-aurora',
        'palette' => ['primary' => '#5937a9', 'primary-dark' => '#472c87', 'accent' => '#d2aae4', 'background' => '#15131b', 'card' => '#1f1c26', 'foreground' => '#f2f1f4', 'muted' => '#b8b4c0', 'border' => '#3d3847', 'tint' => '#24202c'],
        'preset' => [
            'designFamily' => 'contrast', 'heroFill' => false, 'density' => 'standard', 'elevation' => 'soft',
            'font' => 'space', 'radius' => 'default', 'nav' => 'glass',
            'card' => 'gradient', 'button' => 'pill', 'dark' => true,
            'sectionVariants' => [
                'pageheader' => 'pageheader_3',
                'navbar' => 'navbar_8',
                'topbar' => 'topbar_8',
                'hero' => 'hero_8',
                'product' => 'product_3',
                'statistic' => 'statistic_7',
                'feature' => 'feature_8',
                'testimonial' => 'testimonial_2',
                'client' => 'client_8',
                'faq' => 'faq_6',
                'pengumuman' => 'pengumuman_7',
                'cta' => 'cta_8',
                'price' => 'price_8',
                'footer' => 'footer_8',
            ],
            'sectionColors' => [
                'pageheader' => ['bg' => '#15131b', 'text' => '#f2f1f4', 'heading' => '#f2f1f4', 'accent' => '#d2aae4', 'pretext_color' => '#d2aae4', 'text_color' => '#f2f1f4', 'posttext_color' => '#b8b4c0'],
                'navbar' => ['bg' => '#15131b', 'text' => '#f2f1f4', 'heading' => '#f2f1f4', 'accent' => '#d2aae4', 'pretext_color' => '#d2aae4', 'text_color' => '#f2f1f4', 'posttext_color' => '#b8b4c0'],
                'topbar' => ['bg' => '#24202c', 'text' => '#f2f1f4', 'heading' => '#f2f1f4', 'accent' => '#d2aae4', 'pretext_color' => '#d2aae4', 'text_color' => '#f2f1f4', 'posttext_color' => '#b8b4c0'],
                'hero' => ['bg' => '#472c87', 'text' => '#ffffff', 'heading' => '#ffffff', 'accent' => '#ffffff', 'pretext_color' => '#ffffff', 'text_color' => '#ffffff', 'posttext_color' => '#ffffff'],
                'product' => ['bg' => '#15131b', 'text' => '#f2f1f4', 'heading' => '#f2f1f4', 'accent' => '#d2aae4', 'pretext_color' => '#d2aae4', 'text_color' => '#f2f1f4', 'posttext_color' => '#b8b4c0'],
                'statistic' => ['bg' => '#24202c', 'text' => '#f2f1f4', 'heading' => '#f2f1f4', 'accent' => '#d2aae4', 'pretext_color' => '#d2aae4', 'text_color' => '#f2f1f4', 'posttext_color' => '#b8b4c0'],
                'feature' => ['bg' => '#15131b', 'text' => '#f2f1f4', 'heading' => '#f2f1f4', 'accent' => '#d2aae4', 'pretext_color' => '#d2aae4', 'text_color' => '#f2f1f4', 'posttext_color' => '#b8b4c0'],
                'testimonial' => ['bg' => '#15131b', 'text' => '#f2f1f4', 'heading' => '#f2f1f4', 'accent' => '#d2aae4', 'pretext_color' => '#d2aae4', 'text_color' => '#f2f1f4', 'posttext_color' => '#b8b4c0'],
                'client' => ['bg' => '#24202c', 'text' => '#f2f1f4', 'heading' => '#f2f1f4', 'accent' => '#d2aae4', 'pretext_color' => '#d2aae4', 'text_color' => '#f2f1f4', 'posttext_color' => '#b8b4c0'],
                'faq' => ['bg' => '#15131b', 'text' => '#f2f1f4', 'heading' => '#f2f1f4', 'accent' => '#d2aae4', 'pretext_color' => '#d2aae4', 'text_color' => '#f2f1f4', 'posttext_color' => '#b8b4c0'],
                'pengumuman' => ['bg' => '#15131b', 'text' => '#f2f1f4', 'heading' => '#f2f1f4', 'accent' => '#d2aae4', 'pretext_color' => '#d2aae4', 'text_color' => '#f2f1f4', 'posttext_color' => '#b8b4c0'],
                'cta' => ['bg' => '#472c87', 'text' => '#ffffff', 'heading' => '#ffffff', 'accent' => '#ffffff', 'pretext_color' => '#ffffff', 'text_color' => '#ffffff', 'posttext_color' => '#ffffff'],
                'price' => ['bg' => '#15131b', 'text' => '#f2f1f4', 'heading' => '#f2f1f4', 'accent' => '#d2aae4', 'pretext_color' => '#d2aae4', 'text_color' => '#f2f1f4', 'posttext_color' => '#b8b4c0'],
                'footer' => ['bg' => '#15131b', 'text' => '#f2f1f4', 'heading' => '#f2f1f4', 'accent' => '#d2aae4', 'pretext_color' => '#d2aae4', 'text_color' => '#f2f1f4', 'posttext_color' => '#b8b4c0'],
            ],
        ],
    ],
    'enterprise' => [
        'name'        => 'Enterprise',
        'category'    => 'institutional',
        'description' => 'Tampilan profesional monokrom dengan aksen biru, fokus pada kepercayaan dan data.',
        'icon'        => 'shield-check',
        'palette' => ['primary' => '#375ba9', 'primary-dark' => '#2c4987', 'accent' => '#3b329a', 'background' => '#fcfcfd', 'card' => '#ffffff', 'foreground' => '#181c25', 'muted' => '#585e6a', 'border' => '#dadce2', 'tint' => '#eff1f5'],
        'preset' => [
            'designFamily' => 'minimal', 'heroFill' => false, 'density' => 'standard', 'elevation' => 'soft',
            'font' => 'inter', 'radius' => 'square', 'nav' => 'solid',
            'card' => 'elevated', 'button' => 'sharp', 'dark' => false,
            'sectionVariants' => [
                'pageheader' => 'pageheader_4',
                'navbar' => 'navbar_7',
                'topbar' => 'topbar_4',
                'hero' => 'hero_6',
                'product' => 'product_8',
                'statistic' => 'statistic_8',
                'feature' => 'feature_7',
                'testimonial' => 'testimonial_8',
                'client' => 'client_8',
                'faq' => 'faq_1',
                'pengumuman' => 'pengumuman_8',
                'cta' => 'cta_7',
                'price' => 'price_6',
                'footer' => 'footer_5',
            ],
            'sectionColors' => [
                'pageheader' => ['bg' => '#fcfcfd', 'text' => '#181c25', 'heading' => '#181c25', 'accent' => '#375ba9', 'pretext_color' => '#375ba9', 'text_color' => '#181c25', 'posttext_color' => '#585e6a'],
                'navbar' => ['bg' => '#fcfcfd', 'text' => '#181c25', 'heading' => '#181c25', 'accent' => '#375ba9', 'pretext_color' => '#375ba9', 'text_color' => '#181c25', 'posttext_color' => '#585e6a'],
                'topbar' => ['bg' => '#eff1f5', 'text' => '#181c25', 'heading' => '#181c25', 'accent' => '#375ba9', 'pretext_color' => '#375ba9', 'text_color' => '#181c25', 'posttext_color' => '#585e6a'],
                'hero' => ['bg' => '#eff1f5', 'text' => '#181c25', 'heading' => '#181c25', 'accent' => '#375ba9', 'pretext_color' => '#375ba9', 'text_color' => '#181c25', 'posttext_color' => '#585e6a'],
                'product' => ['bg' => '#fcfcfd', 'text' => '#181c25', 'heading' => '#181c25', 'accent' => '#375ba9', 'pretext_color' => '#375ba9', 'text_color' => '#181c25', 'posttext_color' => '#585e6a'],
                'statistic' => ['bg' => '#eff1f5', 'text' => '#181c25', 'heading' => '#181c25', 'accent' => '#375ba9', 'pretext_color' => '#375ba9', 'text_color' => '#181c25', 'posttext_color' => '#585e6a'],
                'feature' => ['bg' => '#fcfcfd', 'text' => '#181c25', 'heading' => '#181c25', 'accent' => '#375ba9', 'pretext_color' => '#375ba9', 'text_color' => '#181c25', 'posttext_color' => '#585e6a'],
                'testimonial' => ['bg' => '#fcfcfd', 'text' => '#181c25', 'heading' => '#181c25', 'accent' => '#375ba9', 'pretext_color' => '#375ba9', 'text_color' => '#181c25', 'posttext_color' => '#585e6a'],
                'client' => ['bg' => '#eff1f5', 'text' => '#181c25', 'heading' => '#181c25', 'accent' => '#375ba9', 'pretext_color' => '#375ba9', 'text_color' => '#181c25', 'posttext_color' => '#585e6a'],
                'faq' => ['bg' => '#fcfcfd', 'text' => '#181c25', 'heading' => '#181c25', 'accent' => '#375ba9', 'pretext_color' => '#375ba9', 'text_color' => '#181c25', 'posttext_color' => '#585e6a'],
                'pengumuman' => ['bg' => '#fcfcfd', 'text' => '#181c25', 'heading' => '#181c25', 'accent' => '#375ba9', 'pretext_color' => '#375ba9', 'text_color' => '#181c25', 'posttext_color' => '#585e6a'],
                'cta' => ['bg' => '#2c4987', 'text' => '#ffffff', 'heading' => '#ffffff', 'accent' => '#ffffff', 'pretext_color' => '#ffffff', 'text_color' => '#ffffff', 'posttext_color' => '#ffffff'],
                'price' => ['bg' => '#fcfcfd', 'text' => '#181c25', 'heading' => '#181c25', 'accent' => '#375ba9', 'pretext_color' => '#375ba9', 'text_color' => '#181c25', 'posttext_color' => '#585e6a'],
                'footer' => ['bg' => '#fcfcfd', 'text' => '#181c25', 'heading' => '#181c25', 'accent' => '#375ba9', 'pretext_color' => '#375ba9', 'text_color' => '#181c25', 'posttext_color' => '#585e6a'],
            ],
        ],
    ],
    'registration' => [
        'name'        => 'Registration',
        'category'    => 'institutional',
        'description' => 'Berorientasi pendaftaran dengan form ringkasan, langkah-langkah, dan testimoni.',
        'icon'        => 'clipboard-check',
        'palette' => ['primary' => '#277771', 'primary-dark' => '#1b5550', 'accent' => '#225268', 'background' => '#fcfdfd', 'card' => '#ffffff', 'foreground' => '#182524', 'muted' => '#586a68', 'border' => '#dae2e1', 'tint' => '#eff5f5'],
        'preset' => [
            'designFamily' => 'studio', 'heroFill' => false, 'density' => 'standard', 'elevation' => 'soft',
            'font' => 'modern', 'radius' => 'rounded', 'nav' => 'solid',
            'card' => 'outline', 'button' => 'default', 'dark' => false,
            'sectionVariants' => [
                'pageheader' => 'pageheader_1',
                'navbar' => 'navbar_2',
                'topbar' => 'topbar_1',
                'hero' => 'hero_2',
                'product' => 'product_1',
                'statistic' => 'statistic_1',
                'feature' => 'feature_1',
                'testimonial' => 'testimonial_1',
                'client' => 'client_1',
                'faq' => 'faq_1',
                'pengumuman' => 'pengumuman_1',
                'cta' => 'cta_1',
                'price' => 'price_1',
                'footer' => 'footer_1',
            ],
            'sectionColors' => [
                'pageheader' => ['bg' => '#fcfdfd', 'text' => '#182524', 'heading' => '#182524', 'accent' => '#277771', 'pretext_color' => '#277771', 'text_color' => '#182524', 'posttext_color' => '#586a68'],
                'navbar' => ['bg' => '#fcfdfd', 'text' => '#182524', 'heading' => '#182524', 'accent' => '#277771', 'pretext_color' => '#277771', 'text_color' => '#182524', 'posttext_color' => '#586a68'],
                'topbar' => ['bg' => '#eff5f5', 'text' => '#182524', 'heading' => '#182524', 'accent' => '#277771', 'pretext_color' => '#277771', 'text_color' => '#182524', 'posttext_color' => '#586a68'],
                'hero' => ['bg' => '#eff5f5', 'text' => '#182524', 'heading' => '#182524', 'accent' => '#277771', 'pretext_color' => '#277771', 'text_color' => '#182524', 'posttext_color' => '#586a68'],
                'product' => ['bg' => '#fcfdfd', 'text' => '#182524', 'heading' => '#182524', 'accent' => '#277771', 'pretext_color' => '#277771', 'text_color' => '#182524', 'posttext_color' => '#586a68'],
                'statistic' => ['bg' => '#eff5f5', 'text' => '#182524', 'heading' => '#182524', 'accent' => '#277771', 'pretext_color' => '#277771', 'text_color' => '#182524', 'posttext_color' => '#586a68'],
                'feature' => ['bg' => '#fcfdfd', 'text' => '#182524', 'heading' => '#182524', 'accent' => '#277771', 'pretext_color' => '#277771', 'text_color' => '#182524', 'posttext_color' => '#586a68'],
                'testimonial' => ['bg' => '#fcfdfd', 'text' => '#182524', 'heading' => '#182524', 'accent' => '#277771', 'pretext_color' => '#277771', 'text_color' => '#182524', 'posttext_color' => '#586a68'],
                'client' => ['bg' => '#eff5f5', 'text' => '#182524', 'heading' => '#182524', 'accent' => '#277771', 'pretext_color' => '#277771', 'text_color' => '#182524', 'posttext_color' => '#586a68'],
                'faq' => ['bg' => '#fcfdfd', 'text' => '#182524', 'heading' => '#182524', 'accent' => '#277771', 'pretext_color' => '#277771', 'text_color' => '#182524', 'posttext_color' => '#586a68'],
                'pengumuman' => ['bg' => '#fcfdfd', 'text' => '#182524', 'heading' => '#182524', 'accent' => '#277771', 'pretext_color' => '#277771', 'text_color' => '#182524', 'posttext_color' => '#586a68'],
                'cta' => ['bg' => '#1b5550', 'text' => '#ffffff', 'heading' => '#ffffff', 'accent' => '#ffffff', 'pretext_color' => '#ffffff', 'text_color' => '#ffffff', 'posttext_color' => '#ffffff'],
                'price' => ['bg' => '#fcfdfd', 'text' => '#182524', 'heading' => '#182524', 'accent' => '#277771', 'pretext_color' => '#277771', 'text_color' => '#182524', 'posttext_color' => '#586a68'],
                'footer' => ['bg' => '#fcfdfd', 'text' => '#182524', 'heading' => '#182524', 'accent' => '#277771', 'pretext_color' => '#277771', 'text_color' => '#182524', 'posttext_color' => '#586a68'],
            ],
        ],
    ],
    'profile' => [
        'name'        => 'Profile',
        'category'    => 'institutional',
        'description' => 'Elegant company profile dengan tipografi serif, kutipan, dan visual bersih.',
        'icon'        => 'building-arch',
        'palette' => ['primary' => '#9e5933', 'primary-dark' => '#7b4528', 'accent' => '#8e762e', 'background' => '#fdfcfc', 'card' => '#ffffff', 'foreground' => '#251d18', 'muted' => '#6a5e58', 'border' => '#e2ddda', 'tint' => '#f5f1ef'],
        'preset' => [
            'designFamily' => 'atelier', 'heroFill' => false, 'density' => 'standard', 'elevation' => 'soft',
            'font' => 'serif', 'radius' => 'default', 'nav' => 'dark',
            'card' => 'solid', 'button' => 'default', 'dark' => false,
            'sectionVariants' => [
                'pageheader' => 'pageheader_2',
                'navbar' => 'navbar_3',
                'topbar' => 'topbar_4',
                'hero' => 'hero_5',
                'product' => 'product_5',
                'statistic' => 'statistic_6',
                'feature' => 'feature_6',
                'testimonial' => 'testimonial_6',
                'client' => 'client_8',
                'faq' => 'faq_5',
                'pengumuman' => 'pengumuman_3',
                'cta' => 'cta_3',
                'price' => 'price_3',
                'footer' => 'footer_6',
            ],
            'sectionColors' => [
                'pageheader' => ['bg' => '#fdfcfc', 'text' => '#251d18', 'heading' => '#251d18', 'accent' => '#9e5933', 'pretext_color' => '#9e5933', 'text_color' => '#251d18', 'posttext_color' => '#6a5e58'],
                'navbar' => ['bg' => '#fdfcfc', 'text' => '#251d18', 'heading' => '#251d18', 'accent' => '#9e5933', 'pretext_color' => '#9e5933', 'text_color' => '#251d18', 'posttext_color' => '#6a5e58'],
                'topbar' => ['bg' => '#f5f1ef', 'text' => '#251d18', 'heading' => '#251d18', 'accent' => '#9e5933', 'pretext_color' => '#9e5933', 'text_color' => '#251d18', 'posttext_color' => '#6a5e58'],
                'hero' => ['bg' => '#f5f1ef', 'text' => '#251d18', 'heading' => '#251d18', 'accent' => '#9e5933', 'pretext_color' => '#9e5933', 'text_color' => '#251d18', 'posttext_color' => '#6a5e58'],
                'product' => ['bg' => '#fdfcfc', 'text' => '#251d18', 'heading' => '#251d18', 'accent' => '#9e5933', 'pretext_color' => '#9e5933', 'text_color' => '#251d18', 'posttext_color' => '#6a5e58'],
                'statistic' => ['bg' => '#f5f1ef', 'text' => '#251d18', 'heading' => '#251d18', 'accent' => '#9e5933', 'pretext_color' => '#9e5933', 'text_color' => '#251d18', 'posttext_color' => '#6a5e58'],
                'feature' => ['bg' => '#fdfcfc', 'text' => '#251d18', 'heading' => '#251d18', 'accent' => '#9e5933', 'pretext_color' => '#9e5933', 'text_color' => '#251d18', 'posttext_color' => '#6a5e58'],
                'testimonial' => ['bg' => '#fdfcfc', 'text' => '#251d18', 'heading' => '#251d18', 'accent' => '#9e5933', 'pretext_color' => '#9e5933', 'text_color' => '#251d18', 'posttext_color' => '#6a5e58'],
                'client' => ['bg' => '#f5f1ef', 'text' => '#251d18', 'heading' => '#251d18', 'accent' => '#9e5933', 'pretext_color' => '#9e5933', 'text_color' => '#251d18', 'posttext_color' => '#6a5e58'],
                'faq' => ['bg' => '#fdfcfc', 'text' => '#251d18', 'heading' => '#251d18', 'accent' => '#9e5933', 'pretext_color' => '#9e5933', 'text_color' => '#251d18', 'posttext_color' => '#6a5e58'],
                'pengumuman' => ['bg' => '#fdfcfc', 'text' => '#251d18', 'heading' => '#251d18', 'accent' => '#9e5933', 'pretext_color' => '#9e5933', 'text_color' => '#251d18', 'posttext_color' => '#6a5e58'],
                'cta' => ['bg' => '#7b4528', 'text' => '#ffffff', 'heading' => '#ffffff', 'accent' => '#ffffff', 'pretext_color' => '#ffffff', 'text_color' => '#ffffff', 'posttext_color' => '#ffffff'],
                'price' => ['bg' => '#fdfcfc', 'text' => '#251d18', 'heading' => '#251d18', 'accent' => '#9e5933', 'pretext_color' => '#9e5933', 'text_color' => '#251d18', 'posttext_color' => '#6a5e58'],
                'footer' => ['bg' => '#fdfcfc', 'text' => '#251d18', 'heading' => '#251d18', 'accent' => '#9e5933', 'pretext_color' => '#9e5933', 'text_color' => '#251d18', 'posttext_color' => '#6a5e58'],
            ],
        ],
    ],
    'campus' => [
        'name'        => 'Campus',
        'category'    => 'institutional',
        'description' => 'Beranda kampus akademik dengan foto, highlight bericon, program, dan statistik.',
        'icon'        => 'school',
        'palette' => ['primary' => '#277771', 'primary-dark' => '#1b5550', 'accent' => '#225268', 'background' => '#fcfdfd', 'card' => '#ffffff', 'foreground' => '#182524', 'muted' => '#586a68', 'border' => '#dae2e1', 'tint' => '#eff5f5'],
        'preset' => [
            'designFamily' => 'gallery', 'heroFill' => false, 'density' => 'standard', 'elevation' => 'soft',
            'font' => 'figtree', 'radius' => 'rounded', 'nav' => 'solid',
            'card' => 'elevated', 'button' => 'default', 'dark' => false,
            'sectionVariants' => [
                'pageheader' => 'pageheader_5',
                'navbar' => 'navbar_5',
                'topbar' => 'topbar_3',
                'hero' => 'hero_3',
                'product' => 'product_7',
                'statistic' => 'statistic_1',
                'feature' => 'feature_6',
                'testimonial' => 'testimonial_2',
                'client' => 'client_6',
                'faq' => 'faq_6',
                'pengumuman' => 'pengumuman_5',
                'cta' => 'cta_4',
                'price' => 'price_1',
                'footer' => 'footer_5',
            ],
            'sectionColors' => [
                'pageheader' => ['bg' => '#fcfdfd', 'text' => '#182524', 'heading' => '#182524', 'accent' => '#277771', 'pretext_color' => '#277771', 'text_color' => '#182524', 'posttext_color' => '#586a68'],
                'navbar' => ['bg' => '#fcfdfd', 'text' => '#182524', 'heading' => '#182524', 'accent' => '#277771', 'pretext_color' => '#277771', 'text_color' => '#182524', 'posttext_color' => '#586a68'],
                'topbar' => ['bg' => '#eff5f5', 'text' => '#182524', 'heading' => '#182524', 'accent' => '#277771', 'pretext_color' => '#277771', 'text_color' => '#182524', 'posttext_color' => '#586a68'],
                'hero' => ['bg' => '#eff5f5', 'text' => '#182524', 'heading' => '#182524', 'accent' => '#277771', 'pretext_color' => '#277771', 'text_color' => '#182524', 'posttext_color' => '#586a68'],
                'product' => ['bg' => '#fcfdfd', 'text' => '#182524', 'heading' => '#182524', 'accent' => '#277771', 'pretext_color' => '#277771', 'text_color' => '#182524', 'posttext_color' => '#586a68'],
                'statistic' => ['bg' => '#eff5f5', 'text' => '#182524', 'heading' => '#182524', 'accent' => '#277771', 'pretext_color' => '#277771', 'text_color' => '#182524', 'posttext_color' => '#586a68'],
                'feature' => ['bg' => '#fcfdfd', 'text' => '#182524', 'heading' => '#182524', 'accent' => '#277771', 'pretext_color' => '#277771', 'text_color' => '#182524', 'posttext_color' => '#586a68'],
                'testimonial' => ['bg' => '#fcfdfd', 'text' => '#182524', 'heading' => '#182524', 'accent' => '#277771', 'pretext_color' => '#277771', 'text_color' => '#182524', 'posttext_color' => '#586a68'],
                'client' => ['bg' => '#eff5f5', 'text' => '#182524', 'heading' => '#182524', 'accent' => '#277771', 'pretext_color' => '#277771', 'text_color' => '#182524', 'posttext_color' => '#586a68'],
                'faq' => ['bg' => '#fcfdfd', 'text' => '#182524', 'heading' => '#182524', 'accent' => '#277771', 'pretext_color' => '#277771', 'text_color' => '#182524', 'posttext_color' => '#586a68'],
                'pengumuman' => ['bg' => '#fcfdfd', 'text' => '#182524', 'heading' => '#182524', 'accent' => '#277771', 'pretext_color' => '#277771', 'text_color' => '#182524', 'posttext_color' => '#586a68'],
                'cta' => ['bg' => '#1b5550', 'text' => '#ffffff', 'heading' => '#ffffff', 'accent' => '#ffffff', 'pretext_color' => '#ffffff', 'text_color' => '#ffffff', 'posttext_color' => '#ffffff'],
                'price' => ['bg' => '#fcfdfd', 'text' => '#182524', 'heading' => '#182524', 'accent' => '#277771', 'pretext_color' => '#277771', 'text_color' => '#182524', 'posttext_color' => '#586a68'],
                'footer' => ['bg' => '#fcfdfd', 'text' => '#182524', 'heading' => '#182524', 'accent' => '#277771', 'pretext_color' => '#277771', 'text_color' => '#182524', 'posttext_color' => '#586a68'],
            ],
        ],
    ],
    'admissions' => [
        'name'        => 'Admissions',
        'category'    => 'institutional',
        'description' => 'Halaman pendaftaran dengan alur langkah, jalur masuk, dan informasi biaya.',
        'icon'        => 'clipboard-list',
        'palette' => ['primary' => '#6137a9', 'primary-dark' => '#4d2c87', 'accent' => '#82329a', 'background' => '#fcfcfd', 'card' => '#ffffff', 'foreground' => '#1d1825', 'muted' => '#5f586a', 'border' => '#dddae2', 'tint' => '#f2eff5'],
        'preset' => [
            'designFamily' => 'institutional', 'heroFill' => false, 'density' => 'standard', 'elevation' => 'soft',
            'font' => 'inter', 'radius' => 'default', 'nav' => 'primary',
            'card' => 'outline', 'button' => 'pill', 'dark' => false,
            'sectionVariants' => [
                'pageheader' => 'pageheader_1',
                'navbar' => 'navbar_2',
                'topbar' => 'topbar_1',
                'hero' => 'hero_1',
                'product' => 'product_2',
                'statistic' => 'statistic_3',
                'feature' => 'feature_3',
                'testimonial' => 'testimonial_3',
                'client' => 'client_1',
                'faq' => 'faq_2',
                'pengumuman' => 'pengumuman_2',
                'cta' => 'cta_3',
                'price' => 'price_4',
                'footer' => 'footer_3',
            ],
            'sectionColors' => [
                'pageheader' => ['bg' => '#fcfcfd', 'text' => '#1d1825', 'heading' => '#1d1825', 'accent' => '#6137a9', 'pretext_color' => '#6137a9', 'text_color' => '#1d1825', 'posttext_color' => '#5f586a'],
                'navbar' => ['bg' => '#fcfcfd', 'text' => '#1d1825', 'heading' => '#1d1825', 'accent' => '#6137a9', 'pretext_color' => '#6137a9', 'text_color' => '#1d1825', 'posttext_color' => '#5f586a'],
                'topbar' => ['bg' => '#f2eff5', 'text' => '#1d1825', 'heading' => '#1d1825', 'accent' => '#6137a9', 'pretext_color' => '#6137a9', 'text_color' => '#1d1825', 'posttext_color' => '#5f586a'],
                'hero' => ['bg' => '#f2eff5', 'text' => '#1d1825', 'heading' => '#1d1825', 'accent' => '#6137a9', 'pretext_color' => '#6137a9', 'text_color' => '#1d1825', 'posttext_color' => '#5f586a'],
                'product' => ['bg' => '#fcfcfd', 'text' => '#1d1825', 'heading' => '#1d1825', 'accent' => '#6137a9', 'pretext_color' => '#6137a9', 'text_color' => '#1d1825', 'posttext_color' => '#5f586a'],
                'statistic' => ['bg' => '#f2eff5', 'text' => '#1d1825', 'heading' => '#1d1825', 'accent' => '#6137a9', 'pretext_color' => '#6137a9', 'text_color' => '#1d1825', 'posttext_color' => '#5f586a'],
                'feature' => ['bg' => '#fcfcfd', 'text' => '#1d1825', 'heading' => '#1d1825', 'accent' => '#6137a9', 'pretext_color' => '#6137a9', 'text_color' => '#1d1825', 'posttext_color' => '#5f586a'],
                'testimonial' => ['bg' => '#fcfcfd', 'text' => '#1d1825', 'heading' => '#1d1825', 'accent' => '#6137a9', 'pretext_color' => '#6137a9', 'text_color' => '#1d1825', 'posttext_color' => '#5f586a'],
                'client' => ['bg' => '#f2eff5', 'text' => '#1d1825', 'heading' => '#1d1825', 'accent' => '#6137a9', 'pretext_color' => '#6137a9', 'text_color' => '#1d1825', 'posttext_color' => '#5f586a'],
                'faq' => ['bg' => '#fcfcfd', 'text' => '#1d1825', 'heading' => '#1d1825', 'accent' => '#6137a9', 'pretext_color' => '#6137a9', 'text_color' => '#1d1825', 'posttext_color' => '#5f586a'],
                'pengumuman' => ['bg' => '#fcfcfd', 'text' => '#1d1825', 'heading' => '#1d1825', 'accent' => '#6137a9', 'pretext_color' => '#6137a9', 'text_color' => '#1d1825', 'posttext_color' => '#5f586a'],
                'cta' => ['bg' => '#4d2c87', 'text' => '#ffffff', 'heading' => '#ffffff', 'accent' => '#ffffff', 'pretext_color' => '#ffffff', 'text_color' => '#ffffff', 'posttext_color' => '#ffffff'],
                'price' => ['bg' => '#fcfcfd', 'text' => '#1d1825', 'heading' => '#1d1825', 'accent' => '#6137a9', 'pretext_color' => '#6137a9', 'text_color' => '#1d1825', 'posttext_color' => '#5f586a'],
                'footer' => ['bg' => '#fcfcfd', 'text' => '#1d1825', 'heading' => '#1d1825', 'accent' => '#6137a9', 'pretext_color' => '#6137a9', 'text_color' => '#1d1825', 'posttext_color' => '#5f586a'],
            ],
        ],
    ],
    'tracer' => [
        'name'        => 'Tracer Study',
        'category'    => 'institutional',
        'description' => 'Jejak alumni dengan dashboard data, metrik lulusan, dan kuesioner tracer.',
        'icon'        => 'chart-bar',
        'palette' => ['primary' => '#2f7592', 'primary-dark' => '#245970', 'accent' => '#2a4583', 'background' => '#fcfdfd', 'card' => '#ffffff', 'foreground' => '#182125', 'muted' => '#58646a', 'border' => '#dadfe2', 'tint' => '#eff3f5'],
        'preset' => [
            'designFamily' => 'bento', 'heroFill' => false, 'density' => 'standard', 'elevation' => 'soft',
            'font' => 'sora', 'radius' => 'rounded', 'nav' => 'glass',
            'card' => 'elevated', 'button' => 'default', 'dark' => false,
            'sectionVariants' => [
                'pageheader' => 'pageheader_7',
                'navbar' => 'navbar_4',
                'topbar' => 'topbar_6',
                'hero' => 'hero_7',
                'product' => 'product_6',
                'statistic' => 'statistic_4',
                'feature' => 'feature_5',
                'testimonial' => 'testimonial_6',
                'client' => 'client_6',
                'faq' => 'faq_7',
                'pengumuman' => 'pengumuman_5',
                'cta' => 'cta_6',
                'price' => 'price_7',
                'footer' => 'footer_6',
            ],
            'sectionColors' => [
                'pageheader' => ['bg' => '#fcfdfd', 'text' => '#182125', 'heading' => '#182125', 'accent' => '#2f7592', 'pretext_color' => '#2f7592', 'text_color' => '#182125', 'posttext_color' => '#58646a'],
                'navbar' => ['bg' => '#fcfdfd', 'text' => '#182125', 'heading' => '#182125', 'accent' => '#2f7592', 'pretext_color' => '#2f7592', 'text_color' => '#182125', 'posttext_color' => '#58646a'],
                'topbar' => ['bg' => '#eff3f5', 'text' => '#182125', 'heading' => '#182125', 'accent' => '#2f7592', 'pretext_color' => '#2f7592', 'text_color' => '#182125', 'posttext_color' => '#58646a'],
                'hero' => ['bg' => '#eff3f5', 'text' => '#182125', 'heading' => '#182125', 'accent' => '#2f7592', 'pretext_color' => '#2f7592', 'text_color' => '#182125', 'posttext_color' => '#58646a'],
                'product' => ['bg' => '#fcfdfd', 'text' => '#182125', 'heading' => '#182125', 'accent' => '#2f7592', 'pretext_color' => '#2f7592', 'text_color' => '#182125', 'posttext_color' => '#58646a'],
                'statistic' => ['bg' => '#eff3f5', 'text' => '#182125', 'heading' => '#182125', 'accent' => '#2f7592', 'pretext_color' => '#2f7592', 'text_color' => '#182125', 'posttext_color' => '#58646a'],
                'feature' => ['bg' => '#fcfdfd', 'text' => '#182125', 'heading' => '#182125', 'accent' => '#2f7592', 'pretext_color' => '#2f7592', 'text_color' => '#182125', 'posttext_color' => '#58646a'],
                'testimonial' => ['bg' => '#fcfdfd', 'text' => '#182125', 'heading' => '#182125', 'accent' => '#2f7592', 'pretext_color' => '#2f7592', 'text_color' => '#182125', 'posttext_color' => '#58646a'],
                'client' => ['bg' => '#eff3f5', 'text' => '#182125', 'heading' => '#182125', 'accent' => '#2f7592', 'pretext_color' => '#2f7592', 'text_color' => '#182125', 'posttext_color' => '#58646a'],
                'faq' => ['bg' => '#fcfdfd', 'text' => '#182125', 'heading' => '#182125', 'accent' => '#2f7592', 'pretext_color' => '#2f7592', 'text_color' => '#182125', 'posttext_color' => '#58646a'],
                'pengumuman' => ['bg' => '#fcfdfd', 'text' => '#182125', 'heading' => '#182125', 'accent' => '#2f7592', 'pretext_color' => '#2f7592', 'text_color' => '#182125', 'posttext_color' => '#58646a'],
                'cta' => ['bg' => '#245970', 'text' => '#ffffff', 'heading' => '#ffffff', 'accent' => '#ffffff', 'pretext_color' => '#ffffff', 'text_color' => '#ffffff', 'posttext_color' => '#ffffff'],
                'price' => ['bg' => '#fcfdfd', 'text' => '#182125', 'heading' => '#182125', 'accent' => '#2f7592', 'pretext_color' => '#2f7592', 'text_color' => '#182125', 'posttext_color' => '#58646a'],
                'footer' => ['bg' => '#fcfdfd', 'text' => '#182125', 'heading' => '#182125', 'accent' => '#2f7592', 'pretext_color' => '#2f7592', 'text_color' => '#182125', 'posttext_color' => '#58646a'],
            ],
        ],
    ],

    // ── UMKM (prototipe pipeline 100 tema) ────────────────────────────
    // Pola: satu tema = satu entri config + satu komponen React + satu blok CSS.
    'umkm_warung' => [
        'name'        => 'Warung & Kuliner',
        'category'    => 'umkm',
        'description' => 'Hangat dan menggugah selera — cocok untuk rumah makan, kafe, dan produk kuliner.',
        'icon'        => 'coffee',
        'palette' => ['primary' => '#a65536', 'primary-dark' => '#83442a', 'accent' => '#967631', 'background' => '#fdfcfc', 'card' => '#ffffff', 'foreground' => '#251c18', 'muted' => '#6a5d58', 'border' => '#e2dcda', 'tint' => '#f5f1ef'],
        'preset' => [
            'designFamily' => 'gallery', 'heroFill' => false, 'density' => 'standard', 'elevation' => 'soft',
            'font' => 'figtree', 'radius' => 'rounded', 'nav' => 'solid',
            'card' => 'elevated', 'button' => 'pill', 'dark' => false,
            'sectionVariants' => [
                'pageheader' => 'pageheader_5',
                'navbar' => 'navbar_5',
                'topbar' => 'topbar_3',
                'hero' => 'hero_3',
                'product' => 'product_7',
                'statistic' => 'statistic_1',
                'feature' => 'feature_6',
                'testimonial' => 'testimonial_2',
                'client' => 'client_6',
                'faq' => 'faq_6',
                'pengumuman' => 'pengumuman_5',
                'cta' => 'cta_4',
                'price' => 'price_1',
                'footer' => 'footer_5',
            ],
            'sectionColors' => [
                'pageheader' => ['bg' => '#fdfcfc', 'text' => '#251c18', 'heading' => '#251c18', 'accent' => '#a65536', 'pretext_color' => '#a65536', 'text_color' => '#251c18', 'posttext_color' => '#6a5d58'],
                'navbar' => ['bg' => '#fdfcfc', 'text' => '#251c18', 'heading' => '#251c18', 'accent' => '#a65536', 'pretext_color' => '#a65536', 'text_color' => '#251c18', 'posttext_color' => '#6a5d58'],
                'topbar' => ['bg' => '#f5f1ef', 'text' => '#251c18', 'heading' => '#251c18', 'accent' => '#a65536', 'pretext_color' => '#a65536', 'text_color' => '#251c18', 'posttext_color' => '#6a5d58'],
                'hero' => ['bg' => '#f5f1ef', 'text' => '#251c18', 'heading' => '#251c18', 'accent' => '#a65536', 'pretext_color' => '#a65536', 'text_color' => '#251c18', 'posttext_color' => '#6a5d58'],
                'product' => ['bg' => '#fdfcfc', 'text' => '#251c18', 'heading' => '#251c18', 'accent' => '#a65536', 'pretext_color' => '#a65536', 'text_color' => '#251c18', 'posttext_color' => '#6a5d58'],
                'statistic' => ['bg' => '#f5f1ef', 'text' => '#251c18', 'heading' => '#251c18', 'accent' => '#a65536', 'pretext_color' => '#a65536', 'text_color' => '#251c18', 'posttext_color' => '#6a5d58'],
                'feature' => ['bg' => '#fdfcfc', 'text' => '#251c18', 'heading' => '#251c18', 'accent' => '#a65536', 'pretext_color' => '#a65536', 'text_color' => '#251c18', 'posttext_color' => '#6a5d58'],
                'testimonial' => ['bg' => '#fdfcfc', 'text' => '#251c18', 'heading' => '#251c18', 'accent' => '#a65536', 'pretext_color' => '#a65536', 'text_color' => '#251c18', 'posttext_color' => '#6a5d58'],
                'client' => ['bg' => '#f5f1ef', 'text' => '#251c18', 'heading' => '#251c18', 'accent' => '#a65536', 'pretext_color' => '#a65536', 'text_color' => '#251c18', 'posttext_color' => '#6a5d58'],
                'faq' => ['bg' => '#fdfcfc', 'text' => '#251c18', 'heading' => '#251c18', 'accent' => '#a65536', 'pretext_color' => '#a65536', 'text_color' => '#251c18', 'posttext_color' => '#6a5d58'],
                'pengumuman' => ['bg' => '#fdfcfc', 'text' => '#251c18', 'heading' => '#251c18', 'accent' => '#a65536', 'pretext_color' => '#a65536', 'text_color' => '#251c18', 'posttext_color' => '#6a5d58'],
                'cta' => ['bg' => '#83442a', 'text' => '#ffffff', 'heading' => '#ffffff', 'accent' => '#ffffff', 'pretext_color' => '#ffffff', 'text_color' => '#ffffff', 'posttext_color' => '#ffffff'],
                'price' => ['bg' => '#fdfcfc', 'text' => '#251c18', 'heading' => '#251c18', 'accent' => '#a65536', 'pretext_color' => '#a65536', 'text_color' => '#251c18', 'posttext_color' => '#6a5d58'],
                'footer' => ['bg' => '#fdfcfc', 'text' => '#251c18', 'heading' => '#251c18', 'accent' => '#a65536', 'pretext_color' => '#a65536', 'text_color' => '#251c18', 'posttext_color' => '#6a5d58'],
            ],
        ],
    ],
];
